### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dudung** [dudung/py-nb#1]
Please leave your suggestion about  [python-jupyter-notebook](https://github.com/dudung/python-jupyter-notebook) here.

You can
+ suggest a topic or a command to be explained in example,
+ correct available examples (please refer to the example, e.g.  [hello_world.ipynb](https://github.com/dudung/python-jupyter-notebook/blob/main/anfang/hello_world.ipynb)),
+ give comment(s) to improve the repository,
+ ask further explanation about an example,
+ propose a link to your repository that is related to this repository.

**Comment by feeskoum** [comment]
@dudung, I wonder if you can add a topic about Markdown syntax that can be used in a Jupyter Notebook file? Thanks.

**Comment by veedasch** [comment]
> @dudung, I wonder if you can add a topic about Markdown syntax that can be used in a Jupyter Notebook file? Thanks.

I would also like to have such guidance as suggested by @feeskoum. Thank you.

**Comment by dudung** [comment]
Examples of Markdown are available [here](https://github.com/dudung/python-jupyter-notebook/tree/main/markdown) and included in [v.0.0.3](https://github.com/dudung/python-jupyter-notebook/releases/tag/v0.0.3), @feeskoum dan @botkoum.

**Comment by RRZahra** [comment]
Selama menggunakan github pada perkuliahan ini masih banyak hal yang belum tereksplor dengan baik. Mohon referensi yang sesuai agar saya dapat menggunakannya dengan labih baik. Terimakasih pak.

**Comment by dudung** [comment]
Iya, betul sekali @RRZahra. Referensi untuk menyunting langsung dengan web browser agak sulit dicari karena umumnya menggunakan aplikasi. Di kuliah belum diajarkan agar tidak terdistraksi ke hal lain.

Salah satunya bisa dengan membaca
+ https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files
+ https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository
+ https://youtu.be/pgzOiH1kmnI

Maaf dengan ketidaknyamanan ini.

**Comment by Abrorisya** [comment]
penjelasan untuk penulisan kode yang menambah directory pencarian diawal soal mungkin di perlukan. saya masih kurang paham tentang sys.path.insert(1, os.path.join(sys.path[0], '../..'))

**Comment by rahmanfaiz** [comment]
Perkuliahan dijalankan dengan baik, hanya ada beberapa masalah koneksi minor ketika kelas. 
Penggunaan github dalam mata kuliah saya rasa cukup unik dan menarik, mengingat github dengan situs git-git lainnya merupakan 'sosial media' dari kebanyakan developer/programmer. Untuk jupyter laiknya dieksplor juga di kelas jadi lebih nyaman dan bisa bertanya lebih leluas, selebihnya sudah sangat baik. 

Terima kasih banyak atas satu semester ini

**Comment by dudung** [comment]
> penjelasan untuk penulisan kode yang menambah directory pencarian diawal soal mungkin di perlukan. saya masih kurang paham tentang sys.path.insert(1, os.path.join(sys.path[0], '../..'))

Ya, benar sekali @Abrorisya. Dikarenakan struktur foldernya adalah

```
┠─ ans
┃  └── 102YYNN
┃      └── hello_student.ipynb
┠─ que 
┠─ src
┃  └── student.py
```

sehingga dari `hello_student.ipynb` perlu naik dua folder yang dilakukan dengan `../..`. Lalu kemudian dilakukan import dengan `src.student` untuk mengambil berkas `student.py` di dalam folder `src`.

**Comment by dudung** [comment]
> Perkuliahan dijalankan dengan baik, hanya ada beberapa masalah koneksi minor ketika kelas.

Noted. Maaf atas ketidaknyamanan ini.

> Penggunaan github dalam mata kuliah saya rasa cukup unik dan menarik, mengingat github dengan situs git-git lainnya merupakan 'sosial media' dari kebanyakan developer/programmer.

Demikian memang tujuannya agar peserta kuliah dapat akrab dengan media sosial programer, mengingat profesi itu dapat pula digeluti oleh alumni fisika.

> Untuk jupyter laiknya dieksplor juga di kelas jadi lebih nyaman dan bisa bertanya lebih leluas, selebihnya sudah sangat baik.

Noted. Thanks.

> Terima kasih banyak atas satu semester ini

Sama-sama, @rahmanfaiz. Semoga bermanfaat.

**Comment by Meykeputri** [comment]
penggunaan mermaid apakah terbatas untuk membuat flowchart? Kalau misalkan ada contoh penggunaan lain, contohnya seperti apa ya?

**Comment by dudung** [comment]
> penggunaan mermaid apakah terbatas untuk membuat flowchart? Kalau misalkan ada contoh penggunaan lain, contohnya seperti apa ya?

Contoh dapat dilihat di https://github.com/mermaid-js/mermaid @Meykeputri dengan beberapa di antaranya adalah seperti di bawah ini.

## pie chart
```mermaid
pie
"Dogs" : 386
"Cats" : 85
"Rats" : 15
```

## state diagram

```mermaid
stateDiagram-v2
[*] --> Still
Still --> [*]
Still --> Moving
Moving --> Still
Moving --> Crash
Crash --> [*]
```

## class diagram

```mermaid
classDiagram
Class01 <|-- AveryLongClass : Cool
<<Interface>> Class01
Class09 --> C2 : Where am i?
Class09 --* C3
Class09 --|> Class07
Class07 : equals()
Class07 : Object[] elementData
Class01 : size()
Class01 : int chimp
Class01 : int gorilla
class Class10 {
  <<service>>
  int id
  size()
}
```

## journey diagram

```mermaid
  journey
    title My working day
    section Go to work
      Make tea: 5: Me
      Go upstairs: 3: Me
      Do work: 1: Me, Cat
    section Go home
      Go downstairs: 5: Me
      Sit down: 3: Me
```

## sequence digram

```mermaid
sequenceDiagram
Alice->>John: Hello John, how are you?
loop Healthcheck
    John->>John: Fight against hypochondria
end
Note right of John: Rational thoughts!
John-->>Alice: Great!
John->>Bob: How about you?
Bob-->>John: Jolly good!
```

**Comment by AkramAkbarAmin** [comment]
Saya ingin tahu kenapa untuk melihat flowchart di Github kita perlu membuat berkas Markdown .md ya Pak? Terimakasih

**Comment by mahaamesha** [comment]
Saya penasaran tentang nilai dinamis di dalam file markdown, Pak. Misalnya jika saya ingin membuat tabel dinamis. Saya terpikir menggunakan metode *file-handling*. Contoh referensi https://www.w3schools.com/python/python_file_handling.asp .

Tapi, jika saya menggunakan metode itu, saya perlu membuka file output, lalu *copy-paste* semua yang ada di dalam file ke `file_notebook.ipynb`. Apa ada cara yang lebih efisien tanpa *copy-paste* dan cukup klik **Run All**, Pak? Terima kasih.

**Comment by JonathanAdriel** [comment]
Terima kasih atas bimbingan Bapak selama satu semester ini. Ada beberapa materi yang sangat berguna yang telah saya aplikasikan pada mata kuliah lain. Sukses dan sehat selalu untuk Bapak...

**Comment by Clarisa00** [comment]
Maaf Pak izin bertanya apakah membuat flowchart pada Jupyter harus menggunakan mermaid? Terimakasih Pak

**Comment by alyarusdiana10** [comment]
Terima kasih kepada Bapak atas ilmu yang telah disampaikan melalui pembelajaran  satu semester ini, karena saya telah mendapatkan banyak ilmu baru terutama mengenai penggunaan GitHub ini yang ternyata banyak manfaatnya dan saya juga bisa lebih eksplor mengenai  pemrograman Python dan Jupyter Notebook selain yang telah diajarkan pada saat waktu TPB. Semoga Bapak sehat selalu 🙂🙏🏻

**Comment by belladhinars** [comment]
Terima kasih banyak untuk ilmunya pak satu semester ini. Sehat selalu, Pak.

**Comment by elenkwan** [comment]
Terimakasih sebelumnya atas ilmu yang telah Bapak berikan, selama pembelajaran menggunakan github saya masih belum paham dengan beberapa fungsi dari beberapa fitur github pak. Apakah ada referensi untuk penjelasan terkait fungsi tersebut Pak?

**Comment by tiaranovis** [comment]
Terimakasih untuk ilmu yang telah bapak ajarkan selama satu semester ini. Saya yang tadinya belum paham apa itu github dan jupyter menjadi tercerahkan dan paham. Sebelumnya apakah ada saran dari Bapak terkait repositori github yang wajib dikunjungi untuk meningkatkan skill coding? terimakasih.

**Comment by dudung** [comment]
> Terimakasih untuk ilmu yang telah bapak ajarkan selama satu semester ini. Saya yang tadinya belum paham apa itu github dan jupyter menjadi tercerahkan dan paham. Sebelumnya apakah ada saran dari Bapak terkait repositori github yang wajib dikunjungi untuk meningkatkan skill coding? terimakasih.

Sama-sama, @tiaranovis. Saran saya cari aplikasi yang menarik dan Tiara ingin berkontribusi. Tidak perlu selalu coding, bisa mulai dari translasi bahasa, membuat dokumentasi dan lainnya.

Misalnya bila tertarik membuat Stiker WA dapat mencoba https://github.com/WhatsApp/stickers (menarik bukan?) atau piranti lunak untuk menggambar seperti Inkscape https://github.com/inkscape/inkscape atau bahkan sumber kode GitHub itu sendiri https://github.com/github

> Yes, we are building GitHub on GitHub. In fact, we’ve been doing this since October 19th, 2007.

Temukan dulu minatnya, lalu ikuti suatu program / organisasi / orang.

Untuk organisasi misalnya ada Microsoft https://github.com/microsoft atau Apple https://github.com/apple (ya, tidak banyak produknya yang Open Source).

**Comment by AslaRoudhatuRohmah** [comment]
Terima kasih atas bimbingan satu semester ini, Pak. Saya merasa senang dapat mengeksplor aplikasi-aplikasi yang menarik seperti github, jupyter notebook, dan lain sebagainya. Semoga bapak sehat selalu.

**Comment by annisakss** [comment]
Terimakasih pak atas ilmu nya untuk satu semester ini, sangat bermanfaat dan menambah wawasan. sehat selalu pak <3

**Comment by anawwaaf** [comment]
Terima kasih pak atas ilmunya untuk satu semester ini. Saya menjadi lebih paham tentang pemrograman python dan penggunaan github dan jupyter. Semoga bapak sehat selalu

**Comment by Ryandwigiantara** [comment]
Terimakasih pak atas ilmu nya untuk satu semester ini

**Comment by dianrae** [comment]
Terima kasih pak atas ilmu yang telah diajarkan selama satu semester. Semoga dengan ilmu ini dapat mempermudah bagi kami dalam menghadapi dunia kerja kedepannya. Tapi saya mengalami kendala pak, hasil tugas flowchart mermaid yg sy kerjakan berhasil pada jupyter. Setelah itu sy upload pada github dan sy cek kembali berkas draw_flowchart_compare_two_numbers.md, hasilnya ga sesuai pak hanya muncul mulai dan selesai. Itu mesti gimana yah pak. Selanjutnya github ini sangat pas apalagi jika ingin digunakan dalam project collab gitu, tapi saya penasaran psk sampai dimana batasan dalam penggunaan github ini?

**Comment by dindafahrila** [comment]
Terimakasih pak atas ilmunya. Saya ada sedikit kendala, karena saya menggunakan macOS sehingga hal tersebut sedikit menyulitkan saya dalam mengerjakan bagian draw flowchart, mungkin apakah ada petunjuk untuk install nb-js-diagrammers di macOS pak?

**Comment by AldianNurAzmar** [comment]
Terimakasih banyak Pak atas ilmu yang telah diberikan dalam bidang komputasi ini, pengalaman secara langsung dalam praktek penggunaan GitHub, Python, Jupyter Notebook, serta Computational Thinking memberikan dampak yang baik kepada kita semua. Semoga kita semua selalu sukses dan sehat selalu.

**Comment by nungkyadw** [comment]
Terimakasih banyak atas ilmunya, Pak. Pembelajaran, tutorial, dan tugas-tugas yang Bapak berikan memberikan pengalaman yang bermanfaat kepada kami, terutama dalam bidang komputasi (GitHub).

**Comment by MarshandaTiana** [comment]
Terima kasih banyak Pak atas seluruh ilmunya yang telah diberikan selama satu semester. Sehat selalu Pak

**Comment by realdhikaarya** [comment]
Saya menyukai mata kuliah ini dan apa yang bapak bawakan bagi kami, sebuah cara yang mungkin baru dan cukup asing bagi kami yang berada di jurusan fisika namun sangat bermanfaat. Saya percaya bahwa mata kuliah ini akan dapat membantu saya dalam banyak hal terutama dalam mengurus project-project tertentu yang source codenya harus didokumentasikan melalui github. Terima kasih banyak bapak :)

**Comment by HanzHamzahK** [comment]
Terima kasih banyak Pak Dudung untuk satu semester ini. Banyak hal yang saya pelajari selama semester yang sangat membantu dalam memecahkan masalah menggunakan komputasi. Tidak lupa juga pengenalan pada GitHub juga sangat menarik dan dapat bisa menjadi inspirasi dalam mengerjakan suatu masalah secara bersama atau mempresentasikan suatu hasil. Terima kasih banyak Pak

**Comment by YodaTaruna** [comment]
Terima kasih banyak Pak Dudung atas ilmu yang bapak berikan. Pembalajaran selama satu semester ini semoga dapat dimanfaatkan dengan baik. Sekali lagi terima kasih dan sehat selalu pak.

**Comment by HartantoWijaya** [comment]
Perkuliahan telah dijalankan dengan baik dan mampu membantu saya untuk memahami penggunaan komputasi dalam menyelesaikan berbagai permasalahan. Kemudian, pengenalan GitHub dan Jupyter Notebook juga sangat berguna terutama karena saya belum pernah menggunakannya. Terima kasih banyak atas ilmu yang telah diberikan selama satu semester ini.

**Comment by 4damrr** [comment]
Kelas ini merupakan salah satu pengalaman belajar terbaik bagi saya selama berkuliah di ITB. Penggunaan Github dan Jupyter Notebook di dalam kelas sangat berguna karena ternyata banyak fitur yang belum sempat saya eksplor sebelumnya. Terima kasih banyak pak Dudung atas ilmu yang bapak berikan. Semoga bapak dan keluarga sehat selalu.

**Comment by iseprobi** [comment]
Terimakasih banyak pak Dudung untuk satu semester ini. Banyak hal baru yang saya pelajari di perkuliahan Fisika Komputasi ini. Penggunaan GitHub ini merupakan salah satu hal yang baru saya pelajari, pembelajaran dengan cara seperti ini cukup menarik.

**Comment by clarissaivana** [comment]
terima kasih banyak pak sebelumnya untuk satu semester ini. saya sangat senang dapat mempelajari banyak hal baru dari mata kuliah ini. saya ingin bertanya pak @dudung , apakah ada aplikasi lain dalam coding yang dapat digunakan untuk membuat flowchart selain menggunakan mermaid ?

**Comment by lasmaevitahelena** [comment]
Terima kasih atas ilmu selama satu semester pak. Pembelajaran sekaligus analisis dengan GitHub dan Jupyter membantu saya memperdalam pemecahan masalah sampai kedetilan. Semoga bapak sehat selalu.

**Comment by dekeu1** [comment]
Terima kasih atas ilmunya selama satu semester pak. Semoga ilmu yang bapak berikan pada semester ini akan berguna untuk kemanusiaan di kedepannya.

**Comment by dimasdaniswara** [comment]
Terima kasih Pak Dudung karena telah membekali kami dengan ilmu yang bermanfaat .

**Comment by rajaabdurafie** [comment]
Terima kasih Pak atas ilmu nya. Bapak baik banget udah ngajarin kita, bikinin file nya rapi jadi kalau mau belajar enak diliatnya, sama bikinin step by step untuk ngerjain UAS. Saya sangat senang dan sangat merasa terbantu dalam pembelajaran Fiskom.

**Comment by shabrinaadhai** [comment]
Terima kasih Pak @dudung  atas ilmu yang telah disampaikan melalui perkuliahan satu semester ini. Disini saya telah mendapatkan banyak ilmu baru terutama mengenai pemrograman Python dan Jupyter Notebook serta ilmu - ilmu lainnya . Terimakasih sekali karena bapak juga selalu bimbing kami step by step di setiap pertemuan kelas .

Sekali lagi terimakasih banyak dan Semoga Bapak sehat selalu 🙏🏻🙂

**Comment by ErvandyR** [comment]
Terima kasih banyak pak @dudung karena telah memberikan pemahaman baru, saya menjadi lebih ingin mendalami dunia ini terutama dalam bahasa pemrograman. Belajar bersama dibawah bimbingan bapak membuat saya menjadi lebih bersemangat karena mudah memahami dan penyampaian yang dibuat sesederhana mungkin sehingga saya paham. Terima kasih banyak pak, sehat selalu untuk bapak dan teman-teman semuanya.

**Comment by Aniesah** [comment]
Terima kasih banyak telah mengajarkan mata kuliah ini. Ternyata banyak hal menarik yang dipelajari selama ini.
Tentang perkuliahan, website berisi materi yang telah disediakan sangat membantu, pengalaman belajar jadi menyenangkan dengan adanya laman tersebut. Tampilannya rapi, bahasanya sangat mudah dipahami.
Mengenai pemberian tugas dan kuis, pemberiannya sangat variatif sehingga merasa tidak terbebani. Selain itu, meskipun asing dengan GitHub, tetapi tidak begitu bermasalah karena petunjuk yang diberikan sangat jelas. Platform yang dikenalkan ini ternyata sangat menarik dan bermanfaat.

**Comment by jeredav24** [comment]
> * o

Terimakasih banyak pak atas ilmunya selama satu semester ini. Saya merasa puas mengenai matakuliah ini karena akhirnya saya dapat belajar menggunakan Github terutama karena banyak sekali kegunaan dari sarana Github serta banyaknya perusahaan teknologi maupun projek projek mandiri yang menggunakan media Github sebagai platform kolaborasi sehingga akan sangat berguna bagi kami untuk kedepannya. Saya harap kedepannya matakuliah ini dapat tetap memberikan materi materi yang relevan dan berguna untuk mahasiswa mahasiswa lainnya.

**Comment by chromaaxion** [comment]
Terima kasih banyak Pak @dudung atas semua ilmunya, penggunaan GitHub menurut saya sangat membantu mahasiswa untuk kedepannya. Selain itu, catatan kuliah yang Bapak berikan sangat jelas dan rapi. Sekali lagi terima kasih banyak Pak.

Mungkin satu saran yang saya ingin berikan untuk mata kuliah ini, adalah diadakannya kembali praktikum fisika komputasi, karena menurut saya matkul ini akan lebih baik jika banyak dipraktekkan.

**Comment by RidwanMSyahrul** [comment]
Terima kasih Pak atas ilmunya selama satu semester ini. Jujur sebelum mengikuti mata kuliah Fiskom ini saya belum mengenal yang namanya GitHub dan setelah mengikuti kelas Bapak, saya bersyukur telah dikenalkan dengan salah satu web open source yang sangat bermanfaat, terutama dalam bidang software development. Guide dan penjelasan dari Bapak juga sangat jelas, rapi, dan mudah dipahami. Semoga kedepannya bisa ditingkatkan lebih baik.

Sehat selalu, Pak!

**Comment by Blitzmaestro** [comment]
> @dudung, I wonder if you can add a topic about Markdown syntax that can be used in a Jupyter Notebook file? Thanks.

Terimakasih pak atas pengajaran dan ilmu yang sudah bapak berikan kepada kami selama satu semester ini. secara keseluruhan, menurut saya penggunaan github sebagai sarana untuk mempelajari coding merupakan pembelajaran yang unik dan menarik. Ada beberapa kekurangan seperti pembiasaan penggunaan github, karena mungkin bagi pemula dalam github, agak sulit untuk menavigasi fungsi fungsi website ini, tetapi ini dapat dengan mudah diselesaikan dengan pembelajaran mandiri. penjelasan bapak pun mudah dimengerti sehingga kami dapat lebih mudah mengerti coding dan cara menggunakan github.

Sehat selalu pak dan mohon maaf atas kesulitan yang saya berikan kepada bapak.

**Comment by Supermieisidua** [comment]
Terima Kasih Pak, Semoga Sehat Selalu Pak

**Comment by nabilaassyf** [comment]
Terima kasih atas ilmu dan pelajarannya Pak Dudung, semoga sehat selalu.

**Comment by amanda248la** [comment]
Terima kasih untuk ilmu yang telah diberikan selama satu semester ini Pak, dan semoga sehat selalu.

**Comment by salmaqilahz** [comment]
Terima kasih banyak pak sudah mengenalkan github dan berbagai library python yang sebelumnya saya tidak tahu. Sangat membantu untuk berkolaborasi secara lebih luas lagi dan efisien ke depannya. Bahan kuliah yang bapak berikan juga sangat membantu karena terdapat referensi yang dapat dibaca. Semoga sehat selalu.

**Comment by RahmaliaNur** [comment]
Terima kasih atas ilmu yang sudah diberikan selama satu semester ini, Pak. Sangat bermanfaat bagi saya yang masih awam. Semoga sehat selalu

**Comment by isnainimufidhatulmughni** [comment]
Terima kasih bapak atas ilmunya. Semoga sehat selalu.
