### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by dudung** [dudung/py-nb#4]
Silakan ajukan pertanyaan terkait pesan kesalahan, misalnya
```
ModuleNotFoundError: No module named 'src'
```

**Comment by shabrinaadhai** [comment]
![image](https://user-images.githubusercontent.com/97967137/167281664-295c91ba-6ac8-4278-94e1-7749dbc6cc74.png)


Assalamu'alaikum...
Maaf pak , saya mau bertanya untuk ujian yg file "hello student" itu kenapa pas diganti nim tapi masih ga bisa jalan ya pak pas di run? dan untuk folder src juga sudah diunduh seluruhnya


Terimakasih pak

**Comment by dudung** [comment]
Saya sudah coba dan berhasil, @shabrinaadhai.

![image](https://user-images.githubusercontent.com/7240685/167291411-4833f38c-693f-4d09-b75f-25fc520ff772.png)

Coba unduh https://github.com/dudung/2021-2-fi3201-01-u2/releases/tag/v0.0.4 untuk [Source code (zip)](https://github.com/dudung/2021-2-fi3201-01-u2/archive/refs/tags/v0.0.4.zip) dan ekstrak.

**Comment by dudung** [comment]
> Assalamu'alaikum... Maaf pak , saya mau bertanya untuk ujian yg file "hello student" itu kenapa pas diganti nim tapi masih ga bisa jalan ya pak pas di run? dan untuk folder src juga sudah diunduh seluruhnya
> 
> Terimakasih pak

Waalaikumsalam wr wb, @shabrinaadhai, apakah setiap sel sudah ditekan Shift-Enter saat mode perintah (Command Mode) dengan garis vertikal berwarna biru di sebelah kirinya? Kelihatannya sel pertama dan kedua belum, ya? Diduga langsung ke sel ketiga.

**Comment by shabrinaadhai** [comment]
> > Assalamu'alaikum... Maaf pak , saya mau bertanya untuk ujian yg file "hello student" itu kenapa pas diganti nim tapi masih ga bisa jalan ya pak pas di run? dan untuk folder src juga sudah diunduh seluruhnya
> > Terimakasih pak
> 
> Waalaikumsalam wr wb, @shabrinaadhai, apakah setiap sel sudah ditekan Shift-Enter saat mode perintah (Command Mode) dengan garis vertikal berwarna biru di sebelah kirinya? Kelihatannya sel pertama dan kedua belum, ya? Diduga langsung ke sel ketiga.

Oh baik pak, akan saya coba kembali dulu ...
Terimakasih pak untuk bantuan dan penjelasannya

**Comment by RidwanMSyahrul** [comment]
Assalamu'alaikum, Pak
mohon maaf izin bertanya, untuk ujian file yang "draw_shapes" saya mencoba code untuk circle dan line tapi error pak dibagian warnanya (ValueError: invalid RGBA argument), ini bagaimana ya pak? Terima kasih sebelunya pak

![msedge_9UHHt9DfBN](https://user-images.githubusercontent.com/97946750/167362481-b5705f75-a05b-4e8c-afe0-2f606770064a.png)
![msedge_k9ymkllgSJ](https://user-images.githubusercontent.com/97946750/167362501-967479df-da45-4f7c-ae35-990c5ef13406.png)

**Comment by RidwanMSyahrul** [comment]
> Assalamu'alaikum, Pak mohon maaf izin bertanya, untuk ujian file yang "draw_shapes" saya mencoba code untuk circle dan line tapi error pak dibagian warnanya (ValueError: invalid RGBA argument), ini bagaimana ya pak? Terima kasih sebelunya pak
> 
> ![msedge_9UHHt9DfBN](https://user-images.githubusercontent.com/97946750/167362481-b5705f75-a05b-4e8c-afe0-2f606770064a.png) ![msedge_k9ymkllgSJ](https://user-images.githubusercontent.com/97946750/167362501-967479df-da45-4f7c-ae35-990c5ef13406.png)

Solved: Sudah teratasi pak, code untuk yg circle saya ganti dari #ccf menjadi #ccccff dan yang line saya ganti dari #4c4 menjadi #44cc44. Terima kasih pak

**Comment by dudung** [comment]
Sama-sama, @RidwanMSyahrul. Maaf baru terbaca pesannya.
