### ISSUE TITLE
Token edunex

### ISSUE THREAD

**Issue by avendeath** [dudung/py-nb#7]
Mohon maaf pak mau bertanya,

Terkait token untuk apply kelas TPJI NT6094 di edunex bagaimana ya? saya kemarin belum tergabung di edunex dikarenakan baru melakukan PRS untuk mata kuliah ini

terima kasih

**Comment by dudung** [comment]
+ @avendeath, selamat bergabung pada NT6094-01.
+ Kelas di Edunex adalah https://edunex.itb.ac.id/courses/47403/preview.
+ Silakan digunakan token `BUKORM` yang berlaku sampai [**22 February 2023 07:16**](),
