### ISSUE TITLE
Pertanyaan tentang FFT

### ISSUE THREAD

**Issue by nungkyadw** [dudung/py-nb#8]
Selamat pagi pak, izin bertanya mengenai hasil dari FFT yang kami peroleh
1. Hasil yang kami dapatkan FFTnya beruma bilangan kompleks, apakah didapatkan hasil seperti ini sudah benar atau ada cara lain dalam mengolah hasil tersebut
2. Dengan menggunakan cara sebelumnya, mengapa didapatkan angkanya sangat besar yaitu 10⁶

Berikut saya tampilkan hasil yang kami dapatkan
![image](https://user-images.githubusercontent.com/97944677/220514120-f9582b58-73f8-4056-81a7-78e7048c967e.png)

![image](https://user-images.githubusercontent.com/97944677/220514169-15829cba-bfc4-4941-ba07-56e37a836f90.png)

**Comment by dudung** [comment]
+ Selamat siang, @nungkyadw. Terima kasih telah memulai untuk berdiskusi.
+ Angka yang besar seperti $10^6$ terkait dengan jumlah bins atau jumlah baris data yang diproses dengan FFT.
+ Bisa lakukan `print(len(yf))` atau `print(len(ryf))` untuk melihat jumlah barisnya? Seharusnya tidak boleh melebihi $10^6$.
+ Hasilnya memang dalam bilangan kompleks, oleh karena itu saat diplot diperlukan `np.abs(yf)` yang akan menghitung nilai absolut $\sqrt{a^2 + b^2}$ dari suatu bilangan kompleks $z = a + ib$.

**Comment by Ryandwigiantara** [comment]
Selamat siang pak, izin bertanya,
saya melakukan FFT dan menemukan error code aligned, setelah dicek data yang diolah memiliki datatype float64
apakah FFT tidak dapat mengolah data type tersebut? karena ada sumber di internet mengakatakan input untuk scipy FFT adalah float32

**Comment by dudung** [comment]
Apakah mirip dengan kasus [ini](https://stackoverflow.com/questions/12307429/scipy-fftpack-and-float64) pesan kesalahannya? Bila ya, dapat digunakan solusi yang ditawarkan.
